### ISSUE TITLE
17px margin

### ISSUE THREAD

**Issue by gbjbaanb** [Alex-D/Trumbowyg#1037]
Looking at the css for trumbowyg 2.19.1, this appears 

```css
.trumbowyg-box,
.trumbowyg-editor {
  display: block;
  position: relative;
  border: 1px solid #DDD;
  width: 100%;
  min-height: 300px;
  margin: 17px auto; }

.trumbowyg-box .trumbowyg-editor {
  margin: 0 auto; }
```

I don't see the reason for having a 17px margin top and bottom for a editor that replaces a textarea that's already defined by the page, even though I can see that removing the margin for an editor area inside a trumbowyg-box div would be necessary.
