### ISSUE TITLE
Integrate Font Awesome SVG icons

### ISSUE THREAD

**Issue by realulim** [Alex-D/Trumbowyg#1087]
I know I can integrate Font Awesome as a webfont by writing CSS like:

```css
.trumbowyg-bold-button:after {
	font-family: "Font Awesome 5\ Free";
	content: "\f032";
}
```

But if I wanted to use Font Awesome's SVG icons, I'd need to use classes like "fas fa-camera" or such. I suppose I could set up a SASS build process and pull the actual class definitions from Font Awesome and insert them in my stylesheet. But maybe I've overlooked a simpler way?
