### ISSUE TITLE
resetCss option does not reset font-weight

### ISSUE THREAD

**Issue by tschoonen** [Alex-D/Trumbowyg#1380]
I got a complaint from a user that he could not get text to be bold. Upon inspection I saw it did successfully put `<strong>` tags around words but it simply did not render it as bold text. I found that because of the stylesheet of my application the text did not appear bold (default weight 300, bold weight 500, which does make a difference in the font we use in the application, but not for Trebuchet MS which is the default Trumbowyg font).

However, the fix was really easy, all I needed to do was augment the -reset-css class with the following:

```css
.trumbowyg-editor.trumbowyg-reset-css {
	font-weight: normal !important;
}
```

**Comment by Alex-D** [comment]
The CSS reset is now simpler to do: 

```css
.trumbowyg-editor.trumbowyg-reset-css {
	all: unset;
}
```
