### ISSUE TITLE
After upgrading to the most recent version, my trumbowyg editor is now as long as the content

### ISSUE THREAD

**Issue by jeremytunnell** [Alex-D/Trumbowyg#1385]
Everything was solid and then I upgraded, and now the trumbowyg editor expands to the length of the content.  For some of my blog posts, the editor is 5000px tall.  

I have added:
autogrow: false,
autogrowOnEnter: false,

Neither of these helps.  Problem exists in both Brave and Firefox on Windows.

I have kind if hacky fixed the problem with:

<style>
.trumbowyg-editor {
max-width:700px;
max-height: 500px;
}
</style>

You can see an example of the problem here :

https://jeremytunnell.net/utils/test_tw

Can you recommend how to fix this correctly?

Thanks,
Jeremy

**Comment by Alex-D** [comment]
I have seen this bug, but I have no room to fix it. For now, you can seed a max height. That is what was set before this update.

**Comment by novotnicek** [comment]
Hello @jeremytunnell @Alex-D 

For "solid" height I using this CSS:

```css
.trumbowyg-box,
.trumbowyg-editor,
.trumbowyg-textarea {
    height: 400px;
}

.trumbowyg-box.trumbowyg-fullscreen,
.trumbowyg-box.trumbowyg-fullscreen .trumbowyg-editor,
.trumbowyg-box.trumbowyg-fullscreen .trumbowyg-textarea {
    height: 100%;
}
```

I don't know, if is really bug  :bug: :thinking:. Seems legit for me.
