### ISSUE TITLE
Basic ul and ol style can be overriden and blanked out

### ISSUE THREAD

**Issue by DrLightman** [Alex-D/Trumbowyg#1505]
Thanks for your editor!

Not sure if an issue with Trumbo, but using it in a project which uses Tailwindcss, the lists are not styled, because TW resets them.

![Image](https://github.com/user-attachments/assets/46806477-b179-4863-b2e2-e6c22f34955c)

Adding the styles by myself such these, fixes it:

```css
.trumbowyg-editor {
    ul, ol { 
        display: block;
        list-style: disc outside none;
        margin: 1em 0;
        padding: 0 0 0 30px;
    }
    ol { 
        list-style-type: decimal;
    }
    
    li { 
        display: list-item;
    }
    
    ul ul, ol ul {
        list-style-type: circle;
        margin-left: 15px; 
    }
    ol ol, ul ol { 
        list-style-type: lower-latin;
        margin-left: 15px; 
    }
}
```

![Image](https://github.com/user-attachments/assets/d21d6e87-5969-4eef-a0f8-d1f38aee30ce)
