### ISSUE TITLE
strike, ol, ul tags not working with reset.css

### ISSUE THREAD

**Issue by sagaritrockz** [Alex-D/Trumbowyg#372]
Browser: FF 48.0.2
OS: Windows 7

Issue: strike, ul, ol tags are not working properly when used with reset.css. 
Is it a known bug ?
Do we have any solution for this ?

Thanks,
Sagar

**Comment by Alex-D** [comment]
What is reset.css?

Maybe you need to add some CSS line to your CSS like:

```css
strike {
    text-decoration: overline;
}
ol, ul {
    margin-left: 20px;
}
ol li, ul li {
    padding-left: 20px;
}
ol {
    list-style: decimal;
}
ul {
    list-style: disc;
}
```
