### ISSUE TITLE
button group splitter will shows at first on the next line

### ISSUE THREAD

**Issue by willzhanglala** [Alex-D/Trumbowyg#707]
### How to reproduce the bug?
1. Make resolution smaller, so that toolbar buttons will be wrapped.
2. Observe the first button group of second line, it will render the seperator.
3. No good looking.

### Suggest:
using ::after instead of ::before, and remove the last seperater
code:
```css
        .trumbowyg-button-pane .trumbowyg-button-group + .trumbowyg-button-group::before {
        content: none; }        
        .trumbowyg-button-pane .trumbowyg-button-group::after {
            content: " ";
            display: inline-block;
            width: 1px;
            background: #d7e0e2;
            margin: 0 5px;
            height: 35px;
            vertical-align: top; }        
        .trumbowyg-button-pane .trumbowyg-button-group:last-child::after {
            content: none; }    
```
