### ISSUE TITLE
Display Icon and Text on Button

### ISSUE THREAD

**Issue by Izuzusama** [Alex-D/Trumbowyg#719]
Is there any way to display icon and button instead of icon or button?

My aim is to display the Icon beside the text so that is easier for users who do not understand the icons.

**Comment by Alex-D** [comment]
You can show icons OR text, but not both.

That's not impossible to do, you can add some CSS with some pseudo-attribute to show title of the icon as text after the element.

```css
.the-icon::after {
  content: attr(title);
}
```

**Comment by Izuzusama** [comment]
Thanks for the guidance, 

Here is the full css incase anyone needs it

```css
.the-icon{
   width: auto !important;
   display: flex !important;
   line-height: 35px;
}
.the-icon::after {
   content: attr(title);
}
```
