### ISSUE TITLE
Issue: Plugins with dropdowns that contain long words or many items

### ISSUE THREAD

**Issue by Braunson** [Alex-D/Trumbowyg#938]
### Informations

**Browser version**: Chrome 73.0.3683.75
**OS**: Win 10
**Screen resolution**: 1920x1080

### How to reproduce the bug?

I've created a custom plugin that's a dropdown the "shortcodes". Two issues persist, when the name of the dropdown item is too long, it drops to the next line but is overlapped by the next item displayed.

Other issue is when there are too many dropdown items it disappears of the screen with no scroll or anything.

Any ideas on (existing?) solutions?

**Comment by Alex-D** [comment]
Since these cases are not existing with plugins/core, I did just not fix that for now.

It's just some CSS to do, feel free to make a Pull Request if you want :)

IMO, a dropdown with so many elements is not really a good idea :/

**Comment by Braunson** [comment]
@Alex-D Thanks, I'll put in a PR soon. The plugin is a list of "shortcodes" for an email template, I'm open to another suggestion in this case?

**Comment by Alex-D** [comment]
No better solution for now. But I keep that in mind for v3 (see #875). I think a better solution should be a select with a filter (dynamic search) to easily go through long list :)

**Comment by Braunson** [comment]
A quick CSS fix for this is (I did this for my plugin specific dropdowns)

```css
.trumbowyg-dropdown-shortcodes {
    max-height: 300px;
    overflow-y: scroll;
}
.trumbowyg-dropdown-shortcodes > button {
    height: initial;
    line-height: 20px;
    padding: 5px 10px !important;
}

```
