### ISSUE TITLE
CSS problem with lang for dropdown link

### ISSUE THREAD

**Issue by miniMAC** [Alex-D/Trumbowyg#956]
Hello! There is a **visual** problem, caused by certain language, in my case "Italian" language. The problem was the **CSS** (width: 200px;) a fixed width declaration.

## The problem

<img width="828" alt="problem" src="https://user-images.githubusercontent.com/1235741/56127548-b2fd3480-5f7d-11e9-9bc2-9ebff26918e8.png">

```css
.trumbowyg-dropdown {
    width: 200px;
    border: 1px solid #ecf0f1;
    padding: 5px 0;
    border-top: none;
    background: #fff;
    margin-left: -1px;
    box-shadow: rgba(0,0,0,.1) 0 2px 3px;
    z-index: 12;
}
```

## The solution

<img width="735" alt="solution" src="https://user-images.githubusercontent.com/1235741/56127565-bbee0600-5f7d-11e9-88f0-5b1aac59bb67.png">

```css
.trumbowyg-dropdown {
    min-width: 200px;
    border: 1px solid #ecf0f1;
    padding: 5px 0;
    border-top: none;
    background: #fff;
    margin-left: -1px;
    box-shadow: rgba(0,0,0,.1) 0 2px 3px;
    z-index: 12;
}
```
