### ISSUE TITLE
Invisible textarea has height of 1px

### ISSUE THREAD

**Issue by dontub** [Alex-D/Trumbowyg#982]
The textarea containing the plain HTML has a height of 1px when it is not visible (so actually it is visible but only 1px of it). This results in a small line between the scroll bar and the bottom border. Is there a reason why height is not set to 0? (I'm using Firefox 67.0.1)

**Comment by Alex-D** [comment]
It's for HTML5 validation purpose.

If you do not need that (no required attribute or so), you can add some CSS like so:

```css
.trumbowyg-box.trumbowyg-editor-visible {
    .trumbowyg-textarea {
		display: none;
    }
}
```

I think it should work ^^

**Comment by dontub** [comment]
Thanks for the quick response. Yes, it works. Just for the record in plain CSS it is:
```css
.trumbowyg-box.trumbowyg-editor-visible .trumbowyg-textarea {
    display: none;
}
```

Actually I can live with the 1px line, though I would suggest to add the following rule to avoid the move of following elements when switching the editor:
```css
.trumbowyg-box.trumbowyg-editor-hidden .trumbowyg-textarea {
    margin-bottom: 1px;
}
```
